CREATE ROLE admin LOGIN PASSWORD '<ADMIN_PASSWORD>';
CREATE ROLE app_write LOGIN PASSWORD '<APP_WRITE_PASSWORD>';
CREATE ROLE app_read LOGIN PASSWORD '<APP_READ_PASSWORD>';

GRANT CONNECT ON DATABASE emotion_diary TO admin;
GRANT CONNECT ON DATABASE emotion_diary TO app_write;
GRANT CONNECT ON DATABASE emotion_diary TO app_read;

GRANT USAGE, CREATE ON SCHEMA public TO admin;
GRANT USAGE ON SCHEMA public TO app_write;
GRANT USAGE ON SCHEMA public TO app_read;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_read;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_write;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;

--PRIVILEGES ON SEQUENCES
DO
$$
DECLARE seq RECORD;
BEGIN
  FOR seq IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'S' AND n.nspname = 'public'
  LOOP
    EXECUTE format('GRANT USAGE, SELECT, UPDATE ON SEQUENCE %I TO app_write;', seq.relname);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I TO app_read;', seq.relname);
    EXECUTE format('GRANT ALL ON SEQUENCE %I TO admin;', seq.relname);
  END LOOP;
END
$$;

ALTER ROLE admin CREATEDB CREATEROLE;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL ON TABLES TO admin;
